-- MySQL Script generated by MySQL Workbench
-- Qui 21 Jul 2016 15:04:12 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus_tracker` DEFAULT CHARACTER SET utf8 ;
USE `bus_tracker` ;

-- -----------------------------------------------------
-- Table `bus_tracker`.`routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`routes` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`routes` (
  `id_routes` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id_routes`))
ENGINE = InnoDB
AUTO_INCREMENT = 105
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`bus` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`bus` (
  `id_bus` INT(11) NOT NULL AUTO_INCREMENT,
  `velocity` DOUBLE NOT NULL,
  `id_routes` INT(11) NOT NULL,
  PRIMARY KEY (`id_bus`),
  CONSTRAINT `fk_bus_routes1`
    FOREIGN KEY (`id_routes`)
    REFERENCES `bus_tracker`.`routes` (`id_routes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`users` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`users` (
  `id_users` INT(11) NOT NULL AUTO_INCREMENT,
  `permission` INT(4) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`notifications_update_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`notifications_update_position` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`notifications_update_position` (
  `email_user` VARCHAR(100) NOT NULL,
  `registration_token_firebase` VARCHAR(45) NOT NULL,
  `id_routes` INT(11) NOT NULL,
  INDEX `fk_config_users_users1_idx` (`id_routes` ASC),
  INDEX `fk_email_users_idx` (`email_user` ASC),
  CONSTRAINT `fk_id_routes`
    FOREIGN KEY (`id_routes`)
    REFERENCES `bus_tracker`.`routes` (`id_routes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_users`
    FOREIGN KEY (`email_user`)
    REFERENCES `bus_tracker`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`last_localizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`last_localizations` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`last_localizations` (
  `id_bus` INT(11) NOT NULL,
  `date` DATETIME NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id_bus`, `date`),
  INDEX `fk_last_localizations_bus1_idx` (`id_bus` ASC),
  CONSTRAINT `fk_last_localizations_bus1`
    FOREIGN KEY (`id_bus`)
    REFERENCES `bus_tracker`.`bus` (`id_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`notifications_bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`notifications_bus` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`notifications_bus` (
  `id_routes` INT(11) NOT NULL AUTO_INCREMENT,
  `id_bus` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `message` VARCHAR(126) NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_routes`),
  CONSTRAINT `fk_notifications_bus1`
    FOREIGN KEY (`id_bus`)
    REFERENCES `bus_tracker`.`bus` (`id_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`points_route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`points_route` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`points_route` (
  `id_routes` INT(11) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id_routes`, `latitude`, `longitude`),
  CONSTRAINT `fk_points_route_routes1`
    FOREIGN KEY (`id_routes`)
    REFERENCES `bus_tracker`.`routes` (`id_routes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bus_tracker`.`schedules_route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_tracker`.`schedules_route` ;

CREATE TABLE IF NOT EXISTS `bus_tracker`.`schedules_route` (
  `id_routes` INT(11) NOT NULL,
  `inicio` VARCHAR(5) NOT NULL,
  `fim` VARCHAR(5) NOT NULL,
  `dias` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_routes`, `inicio`, `fim`, `dias`),
  CONSTRAINT `fk_schedules_route_routes`
    FOREIGN KEY (`id_routes`)
    REFERENCES `bus_tracker`.`routes` (`id_routes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
